server:
  port: 3344

spring:
  application:
    name:  microsoftService-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hjjdazzling/microsoftservice-config.git #GitHub上面的git仓库名字
          username: hjjDazzling
          password: hjj817918.++