spring:
  profiles:
    active:
    - dev
---
spring:
  profiles:
    active: dev
server:
  port: 8888

spring:
  application:
    name: dev


---
spring:
  profiles:
    active: test
server:
  port: 9999
spring:
  application:
    name: test